search: update repo with prod changes
CERNDocumentServer/invenio pull request #231
Opened 2018-07-06 07:11 UTC by ntarocco

@ludmilamarian these are all the changes in `search_engine`. Do you want to keep all or only the `run_on_slave`?

2018-07-09 10:13 UTC, ludmilamarian commented on modules/websearch/lib/search_engine.py
> -        return 'hb'
this should remain.. it looks like it's coming from `legacy`, but we did not deployed it.

2018-07-09 10:16 UTC, ludmilamarian commented on modules/websearch/lib/search_engine.py
ok to commit this part.

2018-07-09 10:16 UTC, ludmilamarian commented on modules/websearch/lib/search_engine.py
we should not commit this one.

2018-07-09 10:17 UTC, ludmilamarian commented on modules/websearch/lib/search_engine.py
> +                        link_ln = "?ln={0}".format(ln)
ok for this one

2018-07-09 10:18 UTC, ludmilamarian requested changes
some of these should not be committed.

2018-07-11 06:31 UTC, ntarocco commented
@ludmilamarian I have applied the changes. Please have a look again.

2018-07-11 12:38 UTC, ludmilamarian approved these changes

2018-07-11 12:39 UTC, ludmilamarian commented
Thanks for the changes! Just one small cosmetic comment for the future: the prefix needs to be the name of the module, in our case `WebSearch`

2018-07-11 12:39 UTC, merged